/******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver
 *
 * Author: Sama Mostafa
 *
 *******************************************************************************/
#include "gpio.h"
#include "icu.h"
#include "common_macros.h" /* To use the macros like SET_BIT */
#include<util/delay.h>
#include <avr/io.h> /* To use ICU/Timer1 Registers */
#include <avr/interrupt.h> /* For ICU ISR */
#include "ultrasonic.h"
#include "std_types.h"
/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;
uint16 g_timePeriod = 0;
uint16 g_PulseHigh = 0;
uint16 period = 0;
uint16 distance = 0;
/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description :
 * Initialize the ICU driver .
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void) {
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = { F_CPU_8, RISING };
	/* Initialize ICU driver */
	Icu_init(&Icu_Config);
	/* Set the trigger bin as output pin  */
	GPIO_setupPinDirection(Trigger_PORT_ID, Trigger_PIN_ID, PIN_OUTPUT);
}
/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void) {
	GPIO_writePin(Trigger_PORT_ID, Trigger_PIN_ID, LOGIC_HIGH); //set trigger bin
	_delay_us(10);
	GPIO_writePin(Trigger_PORT_ID, Trigger_PIN_ID, LOGIC_LOW); //clear trigger bin

}
/*
 * Description :
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void) {
	Ultrasonic_Trigger(); //send the trigger pulse
	if (g_edgeCount == 4) {
		/* calculate the period */
		period = (g_PulseHigh - g_timePeriod); //high time value
		g_edgeCount = 0;
	}
	distance = period * (float32) 0.017; //calculated distance in cm
	return distance;
}
/*
 * Description :
 * This is the call back function called by the ICU driver.
 *  This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void) {
	g_edgeCount++;
	if (g_edgeCount == 1) {
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	} else if (g_edgeCount == 2) {
//		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	} else if (g_edgeCount == 3) {
		/* Store the Period time value */
		g_timePeriod = Icu_getInputCaptureValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	} else if (g_edgeCount == 4) {
		/* Store the Period time value + High time value */
		g_PulseHigh = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}
}
